import { BracketContents } from '@type/bracket';

interface mockRoundData {
  [key: number]: BracketContents;
}

export const matchRoundMock: mockRoundData = {
  1: {
    myGameId: 'NO_DATA',
    matchInfoDtoList: [
      {
        matchName: 'Group A',
        matchLink: '10-8878-debc6c12b149',
        matchStatus: 'READY',
        matchRound: 64,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
            profileSrc: '/profileTest.jpg',
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group B',
        matchLink: '48-96cb-a4f9c58ce387',
        matchStatus: 'READY',
        matchRound: 64,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미7',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId3',
            gameTier: 'iron ii',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미10',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미3',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미11',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'DummyGameId1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group C',
        matchLink: '48-96cb-a4f9c58ce387',
        matchStatus: 'READY',
        matchRound: 64,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미7',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId3',
            gameTier: 'iron ii',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미10',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미3',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미11',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'DummyGameId1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group D',
        matchLink: '48-96cb-a4f9c58ce387',
        matchStatus: 'READY',
        matchRound: 64,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미7',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId3',
            gameTier: 'iron ii',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미10',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미3',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미11',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'DummyGameId1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group E',
        matchLink: '10-8878-debc6c12b149',
        matchStatus: 'READY',
        matchRound: 64,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group F',
        matchLink: '48-96cb-a4f9c58ce387',
        matchStatus: 'READY',
        matchRound: 32,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미7',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId3',
            gameTier: 'iron ii',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미10',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미3',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미11',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'DummyGameId1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group G',
        matchLink: '48-96cb-a4f9c58ce387',
        matchStatus: 'READY',
        matchRound: 32,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미7',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId3',
            gameTier: 'iron ii',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미10',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미3',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미11',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'DummyGameId1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group H',
        matchLink: '48-96cb-a4f9c58ce387',
        matchStatus: 'READY',
        matchRound: 32,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미7',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId3',
            gameTier: 'iron ii',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미10',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미3',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미11',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'DummyGameId1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
    ],
  },
  2: {
    myGameId: 'NO_DATA',
    matchInfoDtoList: [
      {
        matchName: 'Group A',
        matchLink: '10-8878-debc6c12b149',
        matchStatus: 'READY',
        matchRound: 32,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group B',
        matchLink: '48-96cb-a4f9c58ce387',
        matchStatus: 'READY',
        matchRound: 32,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미7',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId3',
            gameTier: 'iron ii',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미10',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미3',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미11',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'DummyGameId1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group C',
        matchLink: '48-96cb-a4f9c58ce387',
        matchStatus: 'READY',
        matchRound: 32,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미7',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId3',
            gameTier: 'iron ii',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미10',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미3',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미11',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'DummyGameId1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group D',
        matchLink: '48-96cb-a4f9c58ce387',
        matchStatus: 'READY',
        matchRound: 32,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미7',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId3',
            gameTier: 'iron ii',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미10',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미3',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미11',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'DummyGameId1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
    ],
  },
  3: {
    myGameId: 'NO_DATA',
    matchInfoDtoList: [
      {
        matchName: 'Group A',
        matchLink: '10-8878-debc6c12b149',
        matchStatus: 'READY',
        matchRound: 16,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group B',
        matchLink: '48-96cb-a4f9c58ce387',
        matchStatus: 'READY',
        matchRound: 16,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미7',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId3',
            gameTier: 'iron ii',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미10',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미3',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미11',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'DummyGameId1',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
    ],
  },
  4: {
    myGameId: 'NO_DATA',
    matchInfoDtoList: [
      {
        matchName: 'Group A',
        matchLink: '10-8878-debc6c12b149',
        matchStatus: 'READY',
        matchRound: 8,
        matchRoundCount: 0,
        matchRoundMaxCount: 1,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
    ],
  },
};
