import { BracketContents } from '@type/bracket';

interface mockRoundData {
  [key: number]: BracketContents;
}

export const matchRoundMock: mockRoundData = {
  1: {
    myGameId: 'NO_DATA',
    matchInfoDtoList: [
      {
        matchName: 'Group A',
        matchId: 5345,
        matchStatus: 'READY',
        matchRound: 64,
        matchCurrentSet: 2,
        matchSetCurrent: 3,
        alarm: true,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
            profileSrc: '/profileTest.jpg',
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group B',
        matchId: 53454,
        matchStatus: 'READY',
        matchRound: 64,
        matchCurrentSet: 2,
        matchSetCurrent: 3,
        alarm: true,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
            profileSrc: '/profileTest.jpg',
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group C',
        matchId: 535145,
        matchStatus: 'READY',
        matchRound: 64,
        matchCurrentSet: 2,
        matchSetCurrent: 3,
        alarm: true,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
            profileSrc: '/profileTest.jpg',
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group D',
        matchId: 534655,
        matchStatus: 'READY',
        matchRound: 64,
        matchCurrentSet: 2,
        matchSetCurrent: 3,
        alarm: true,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
            profileSrc: '/profileTest.jpg',
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
    ],
  },
  2: {
    myGameId: 'NO_DATA',
    matchInfoDtoList: [
      {
        matchName: 'Group A',
        matchId: 5345,
        matchStatus: 'READY',
        matchRound: 64,
        matchCurrentSet: 2,
        matchSetCurrent: 3,
        alarm: true,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
            profileSrc: '/profileTest.jpg',
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
      {
        matchName: 'Group B',
        matchId: 53454,
        matchStatus: 'READY',
        matchRound: 64,
        matchCurrentSet: 2,
        matchSetCurrent: 3,
        alarm: true,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
            profileSrc: '/profileTest.jpg',
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
    ],
  },
  3: {
    myGameId: 'NO_DATA',
    matchInfoDtoList: [
      {
        matchName: 'Group A',
        matchId: 5345,
        matchStatus: 'READY',
        matchRound: 64,
        matchCurrentSet: 2,
        matchSetCurrent: 3,
        alarm: true,
        matchPlayerInfoList: [
          {
            gameId: '더미8',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
            profileSrc: '/profileTest.jpg',
          },
          {
            gameId: '더미0',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미6',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미4',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미9',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미2',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: '더미5',
            gameTier: 'platinum',
            playerStatus: 'WAITING',
            score: 0,
          },
          {
            gameId: 'participantGameId2',
            gameTier: 'platinum ii',
            playerStatus: 'WAITING',
            score: 0,
          },
        ],
      },
    ],
  },
};
